services:
  # Frontend - Static Site
  - type: web
    name: barbearia-frontend
    env: static
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: ./frontend/build
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend - Web Service
  - type: web
    name: barbearia-backend
    env: node
    plan: free
    region: oregon
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: barbearia-backend
          property: port
      - key: DATABASE_URL
        fromDatabase:
          name: barbearia-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://barbearia-frontend.onrender.com
      - key: EMAILJS_SERVICE_ID
        sync: false
      - key: EMAILJS_TEMPLATE_ID
        sync: false
      - key: EMAILJS_PUBLIC_KEY
        sync: false

# Database
databases:
  - name: barbearia-db
    databaseName: barbearia_solidaria
    user: barbearia_user
    plan: free
    region: oregon
    postgresMajorVersion: 15