services:
  # Backend - Web Service (Updated: 2025-01-12 - Runtime Fix)
  - type: web
    name: barbearia-backend
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: barbearia-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://barbearia-frontend.onrender.com
      - key: EMAILJS_SERVICE_ID
        sync: false
      - key: EMAILJS_TEMPLATE_ID
        sync: false
      - key: EMAILJS_PUBLIC_KEY
        sync: false

  # Frontend - Static Site
  - type: web
    name: barbearia-frontend
    env: static
    buildCommand: cd frontend && node build-render.js
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

# Database
databases:
  - name: barbearia-db
    databaseName: barbearia_solidaria
    user: barbearia_user
    plan: free
    region: oregon
    postgresMajorVersion: 15